### ISSUE TITLE
Normalize first `M`?

### ISSUE THREAD

**Issue by tomekwi** [jkroso/parse-svg-path#2]
From [SVG 1.1 specs](http://www.w3.org/TR/SVG/paths.html#PathData):

> If a relative moveto (m) appears as the first element of the path, then it is treated as a pair of absolute coordinates.

How about normalizing the first `m` to always be an absolute `M`?

**Comment by tomekwi** [comment]
Since these two paths are equvalent, shouldn’t they result in equivalent output?

```js
parse('m1,2 3,4')   // » [ [ 'm', 1, 2 ], [ 'l', 3, 4 ] ]
parse('M1,2 l3,4')  // » [ [ 'M', 1, 2 ], [ 'l', 3, 4 ] ]
```

**Comment by jkroso** [comment]
Its the rendering engine that doesn't care. I don't think the parser needs to have this built in

**Comment by jkroso** [comment]
Or at least it _could_ be done in the renderer I mean

**Comment by tomekwi** [comment]
well, the parser already normalizes stuff. `m1,2 3,4` produces the same result as `m1,2 l3,4`.

**Comment by jkroso** [comment]
True. But in that case I think its __always__ the right thing to do in terms of the semantic meaning of the path. You could argue the spec is more focused on making rendering engines consistent than defining what the semantics of the syntax should mean. IMO if you start with a relative `m` you mean start from wherever you finished last

**Comment by tomekwi** [comment]
> IMO if you start with a relative m you mean start from wherever you finished last

Yeah that’s how I understood it as well. But then the specs and the behavior of renderers got me puzzled.

But I see your point. I’m using your lib together with your `abs-svg-path` anyway. Closing this then.
